### ISSUE TITLE
RTX 2060 being read as a GTX 470 in Proton games.

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/wine#42]
I've noticed that in games that like to identify the GPU (two games in question were Flatout2 (dx9 game) and Skyrim Special Edition (DX11/dxvk game)) that my laptop's RTX 2060 is being read as a GTX 470.

This strikes me as more than a little bit odd, not sure how much of a problem it could actually be as the games run fine, but it's one of those little things that might get confusing on occasion. 

I imagine it's possible that other RTX series cards have a similar issue.

**Comment by aeikum** [comment]
Unfortunately it's expected behavior. Lots of games are written to assume they can use some nvidia-specific features if they detect an nvidia card, and crash if they can't use those features. So we pretend all nvidia cards are actually AMD cards, see 1091eaf13692b16ed66328ceeebfc587075fec6c. Of the options we have, we decided this was the least bad.

**Comment by kisak-valve** [comment]
Upstream wine hasn't been taught to identify GTX 2xxx cards yet (https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/wined3d/adapter_gl.c#l1301), so it's falling back to a generic DX11-capable nvidia card https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/wined3d/directx.c#l641 which happens to be a GTX 470.

This should only be a cosmetic issue and will eventually be resolved upstream.

**Comment by Rabcor** [comment]
Allright, thanks, I at least know what it is now. Still; why is it read as a GTX 470 if it is supposed to be read as an AMD card?

**Comment by kisak-valve** [comment]
Upstream commit: https://source.winehq.org/git/wine.git/commit/ad907fd12ee48b3558a7e499d289cef21e920a08
