### ISSUE TITLE
Drop "wine.inf: apply LargeAddressAware fix for Bayonetta"

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/wine#64]
e921eb5e356ef33241be5f770b47f3945bdcfb16 has been made redundant by the app_compat_configs in 891390:

https://steamdb.info/app/891390/

It should be dropped from the proton patch set.

**Comment by ryao** [comment]
@Plagman Is there any reason that you could see for continuing to carry this patch?

**Comment by aeikum** [comment]
Technically using the compat config var is incorrect, as it will affect all processes in the prefix, which could cause executables that are non-LAA to crash. In practice I doubt this matters. Reverting seems fine, I'd be happy to drop a diff. I'll try to remember to do this during the next Wine rebase.

**Comment by kakra** [comment]
Maybe the config var should be extended to optionally give it a exename, i.e. `CONFIGVAR="bayonetta.exe=yes:launcher.exe=no"`

**Comment by pchome** [comment]
@aeikum 
I doubt AppDefaults are working since `steam.exe` helper was introduced.
I tried to create some overrides in `HKCU,Software\Wine\AppDefaults\` and none of them work for me. At the same time `HKCU,Software\Wine\AppDefaults\steam.exe\` are fine and applied to all apps launched in this prefix.

**Comment by aeikum** [comment]
@pchome Can you go into more detail? It seems to be working for me. I tested with the LargeAddressAware appdefault.

**Comment by pchome** [comment]
Sure. I forced Wine virtual desktop mode for one prefix, and there is an annoying thing with the Wine virtual desktop mode -- sometimes empty virtual desktop window "flashing" several times before the game actual launch.

I tested on regular wine, trying to avoid such unwanted behaviour, and figured out this caused by `wineboot.exe`. For Proton it also can be `iscriptevaluator.exe`, but I can't check.

Here are the overrides, which I used for testing, and which work in regular Wine, but have no effect in wine-proton:
```reg
[HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops]
"Default"="1920x1080"
"regedit.exe"=""
"wineboot.exe"=""

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\regedit.exe\Explorer]
"Desktop"="regedit.exe"
[HKEY_CURRENT_USER\Software\Wine\AppDefaults\wineboot.exe\Explorer]
"Desktop"="wineboot.exe"
```
In this particular case, there is no virtual desktop window for the regedit.exe, also not "flashing" before e.g. winecfg.exe was opened in the virtual desktop mode (as expected).

I might be wrong, and the AppDefaults are fine in general, but broken only in case of Wine virtual desktop mode. I didn't tested any other overrides under `HKEY_CURRENT_USER\Software\Wine\AppDefaults` key.

**Comment by aeikum** [comment]
Yeah, I think that's just a quirk of how the virtual desktop works. I suspect you'd get substantially similar results with upstream Wine. I believe the desktop window is actually managed by explorer.exe. I'm not sure how the Desktop appdefault functions with regard to the window that explorer manages.

**Comment by aeikum** [comment]
> Technically using the compat config var is incorrect, as it will affect all processes in the prefix, which could cause executables that are non-LAA to crash. In practice I doubt this matters. Reverting seems fine, I'd be happy to drop a diff. I'll try to remember to do this during the next Wine rebase.

I remembered! This was dropped in the 5.0 rebase.
