### ISSUE TITLE
Memory Swap | Performance improved on computer with minimal memory.

### ISSUE THREAD

**Issue by Veinzer** [ValveSoftware/wine#79]
Hello the physic memory in wine is swap + ram, but swap is instable and cause bug on game become Call of duty... Just add PROTON_IGNORE_SWAP=1 ? Thanks for read my message

**Comment by kakra** [comment]
It doesn't seem so:
![image](https://user-images.githubusercontent.com/17684/74566470-d022db00-4f73-11ea-8615-c1b325e39c7b.png)
My system has 32G of memory, and this is shown as physical memory. Where do you get your information from? The only value that could explain your observation would be "commit charge" but a game shouldn't really interpret that as physical memory.

**Comment by Veinzer** [comment]
U have swap memory?

**Comment by Veinzer** [comment]
On cod aw detect swap become physical memory

**Comment by kakra** [comment]
> U have swap memory?

Yes, 66 GB... Mainly for hibernate tho that feature doesn't work for me (but I didn't try in a long time). You should never run without at least a minimal amount swap. My system has 77 MB currently swapped out.

If you're seeing performance problems in games and you suspect that being due to swapping, I have a few ideas to check:

1. Maybe you've "tuned" the memory subsystem of your kernel wrong. `vm.swappiness` is such a parameter. You shouldn't put that too low although many recommend it. Tuning it too low sacrifices cache memory for not swapping. This is usually a very bad deal for running just a single application in foreground: Your game. I recommend leaving it at 60% (default) or not going below 30%. When your cache memory drops below 1-2 GB (from my observation), FS performance becomes sluggish, depending on the file system.

2. Maybe you or your distribution enabled zswap with a too big pool size. This can lead to phantom swap storms. Try turning it off or decrease it from default 20% to 5% or even 3%.

3. Quit browsers (or tabs) while playing, they tend to occupy a lot of memory both from VRAM and system RAM for their composition pipelines, and that cannot be made available to games: Most graphics drivers in Linux do not support swapping or voluntarily freeing their memory yet.


> On cod aw detect swap become physical memory

I'm not sure what you mean. I don't know Call of Duty. And I'm unsure what "aw" means. But that may be a side effect of using zswap.
